### PR TITLE
Copy layout/styles from main website

### PR DESCRIPTION
**Pull request by jvatic**
screen shot 2016-07-25 at 17 58 49
screen shot 2016-07-25 at 17 57 31
screen shot 2016-07-25 at 17 57 37

### CODE REVIEW

**Comment by titanous** [comment]
Cool, can you add a docs link to the top as well?

**Comment by jvatic** [comment]
Added docs link

**Comment by titanous** [comment]
LGTM

**Comment by lmars** [comment]
@jvatic looks good :smile:

**Pull request merged**
